# Generated by Django 3.2.16 on 2024-11-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241109_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='game_state',
            field=models.TextField(),
        ),
    ]
