# Generated by Django 3.2.16 on 2024-12-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gamestate_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='ship_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
