# Generated by Django 3.2.16 on 2025-01-11 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gamestate_ship_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_game', models.DateTimeField(auto_now_add=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
