# Generated by Django 3.2.16 on 2025-01-25 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gamelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='game_state',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='player',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='game_state_1',
            field=models.TextField(default={}),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='game_state_2',
            field=models.TextField(default={}),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_1', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_2', to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_1_gl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_2_gl', to=settings.AUTH_USER_MODEL),
        ),
    ]
